# Generated by Django 5.2.1 on 2025-05-21 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_step_voting_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firststep',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='secondstep',
            name='first_step',
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255)),
                ('description', models.TextField(blank=True, default='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='firststep',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_step', to='two_step_voting_app.votingsession'),
        ),
        migrations.AddField(
            model_name='secondstep',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_step', to='two_step_voting_app.votingsession'),
        ),
        migrations.AddField(
            model_name='topic',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='two_step_voting_app.votingsession'),
        ),
    ]
