# Generated by Django 5.2.1 on 2025-05-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_step_voting_app', '0002_remove_firststep_topic_remove_secondstep_first_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firststepvote',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_step_Vote', to='two_step_voting_app.votingsession'),
        ),
        migrations.AddField(
            model_name='secondstepvote',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_step_Vote', to='two_step_voting_app.votingsession'),
        ),
    ]
