# Generated by Django 5.2.1 on 2025-05-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_step_voting_app', '0003_firststepvote_session_secondstepvote_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='session_Image',
            field=models.ImageField(default='session_Image', upload_to='session_Image'),
        ),
    ]
