# Generated by Django 5.2.1 on 2025-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_step_voting_app', '0004_votingsession_session_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firststep',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
